#BSUB -J index
#BSUB -n 6
#BSUB -R span[hosts=1]
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -q normal


for i in 5H6-7-1 5H6-7-2 5H7-8-1 5H7-8-2 5H8-9-1 5H8-9-2 5H9-10-1 5H9-10-2 5N6-7-1 5N6-7-2 5N7-8-1 5N7-8-2 5N8-9-1 5N8-9-2 5N9-10-1 5N9-10-2 9H6-7-1 9H6-7-2 9H7-8-1 9H7-8-2 9H8-9-1 9H8-9-2 9H9-10-1 9H9-10-2 9N6-7-1 9N6-7-2 9N7-8-1 9N7-8-2 9N8-9-1 9N8-9-2 9N9-10-1 9N9-10-2
do

bowtie -q -p 6 -v 0 --un ${i}_clean.fq /public/home/phwan/smallRNA_new/4.Rfam_index/Rfam/database/Rfamdatabase /public/home/phwan/smallRNA_new/2.clean_data/Fastq/${i}_clean.fq ${i}_clean_Rfam 2> Rfam_fa/${i}.log

done

mv *clean_Rfam* Rfam_fa/

