#BSUB -J getphsirna
#BSUB -n 6
#BSUB -R span[hosts=1]
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -q q2680v2
for i in 5H6-7 5H7-8 5H8-9 5H9-10 5N6-7 5N7-8 5N8-9 5N9-10 9H6-7 9H7-8 9H8-9 9H9-10 9N6-7 9N7-8 9N8-9 9N9-10
do
mkdir -p ./${i}
sRNAminer phasiRNA_identification_no_align -p 6 --phasiRNA_len 24 -i /public/home/phwan/smallRNA_new/sRNAminer/3.bowtie_to_sRNAminer/Bowtie_to_sRNAminer${i}/${i}-1_mapping_last.bowtie.aln.sorted,/public/home/phwan/smallRNA_new/sRNAminer/3.bowtie_to_sRNAminer/Bowtie_to_sRNAminer${i}/${i}-2_mapping_last.bowtie.aln.sorted -g /public/home/phwan/smallRNA_new/3.Gbar_gene_index/Gbarbadense_genome_HAU_v2.0.fasta -o ./${i}
done

for i in 5H6-7 5H7-8 5H8-9 5H9-10 5N6-7 5N7-8 5N8-9 5N9-10 9H6-7 9H7-8 9H8-9 9H9-10 9N6-7 9N7-8 9N8-9 9N9-10
do
mkdir -p ./${i}
sRNAminer hc-siRNA_locus_identification -m 0 -g /public/home/phwan/smallRNA_new/3.Gbar_gene_index/Gbarbadense_genome_HAU_v2.0.fasta --index /public/home/phwan/smallRNA_new/3.Gbar_gene_index/Gbarbadense_genome_HAU -i /public/home/phwan/smallRNA_new/sRNAminer/1.Seq_collapsing/${i}-1_clean.mc.fa,/public/home/phwan/smallRNA_new/sRNAminer/1.Seq_collapsing/${i}-2_clean.mc.fa --PHAS24_file /public/home/phwan/smallRNA_new/sRNAminer/5.hc-siRNA/1.hc-siRNA_identification/step1_phasiRNA/${i}/phasiRNA_identification/merged.24.PHAS.list.filter.xls -o ./${i}
done






