#BSUB -J c5H6-7-1
#BSUB -n 5
#BSUB -R span[hosts=1]
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -q q2680v2


zcat /public/home/phwan/Gossypium-barbadense/Rawdata/clean1/5H6-7-1/5H6-7-1_13_1_clean1.fastq.gz /public/home/phwan/Gossypium-barbadense/Rawdata/clean1/5H6-7-1/5H6-7-1_14_1_clean1.fastq.gz | gzip > /public/home/phwan/Gossypium-barbadense/Rawdata/clean1/5H6-7-1/5H6-7-1_1_clean1.fastq.gz

zcat /public/home/phwan/Gossypium-barbadense/Rawdata/clean1/5H6-7-1/5H6-7-1_13_2_clean2.fastq.gz /public/home/phwan/Gossypium-barbadense/Rawdata/clean1/5H6-7-1/5H6-7-1_14_2_clean2.fastq.gz | gzip > /public/home/phwan/Gossypium-barbadense/Rawdata/clean1/5H6-7-1/5H6-7-1_2_clean2.fastq.gz


